---
stages:
- name: PREPARE
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: SCRIPT_URL
    value: 'https://raw.githubusercontent.com/jt-nti/build-lib/53-sample-builds/src'
    type: text
  jobs:
  - name: Prepare
    type: builder
    script: |-
      #!/bin/bash
      source <(curl -sSL "${SCRIPT_URL}/prepare-unstable.sh")
- name: BUILD
  inputs:
  - type: job
    stage: PREPARE
    job: Prepare
  triggers:
  - type: stage
  properties:
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  jobs:
  - name: Build
    type: builder
    script: |-
      #!/bin/bash
      source "${SCRIPT_DIR}/router.sh" build sample
- name: "DEPLOY"
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REGION_ID
    value: ${REGION_ID}
    type: text
  - name: SCRIPT_DIR
    value: ${SCRIPT_DIR}
    type: text
  - name: BLOCKCHAIN_SERVICE_INSTANCE
    value: ${BLOCKCHAIN_SERVICE_INSTANCE}
    type: text
  - name: CLOUDANT_SERVICE_INSTANCE
    value: ${CLOUDANT_SERVICE_INSTANCE}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${APP_NAME}
    script: |-
      #!/bin/bash
      source "${SCRIPT_DIR}/router.sh" deploy sample